/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetofinal_aed2_lp2;

import edu.princeton.cs.algs4.DijkstraSP;
import edu.princeton.cs.algs4.FlowEdge;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import projetofinal_aed2_lp2.aux.GrafoDirigido;
import projetofinal_aed2_lp2.aux.NoFonteEnergia;
import projetofinal_aed2_lp2.aux.NoMoradia;

/**
 *
 * @author patricia
 */
public class InterfaceGrafic extends javax.swing.JFrame {

    private GrafoDirigido grafo;
    private ArrayList<RedeEletrica> redes = new ArrayList<>();
    private ArrayList<FonteEnergiaG> fontes = new ArrayList<>();
    private ArrayList<Moradia> moradias = new ArrayList<>();
    
    /**
     * Creates new form InterfaceGrafic
     * Define alguns componentes como invisiveis e remove todos os items das ComboBox.
     */
    public InterfaceGrafic() {
        initComponents();
        this.jComboBoxMoradias.setVisible(false);
        this.jTextAreaGrafo.setVisible(false);
        this.jButtonInserirContador.setVisible(false);
        this.jButtonRemContador.setVisible(false);
        this.jButtonInserirFonte.setVisible(false);
        this.jButtonRemFonte.setVisible(false);
        this.jComboBoxInsRemCont.setVisible(false);
        this.jComboBoxInsRemFonte.setVisible(false);
        this.jComboBoxInsRemCont.removeAllItems();
        this.jComboBoxInsRemFonte.removeAllItems();
        this.jComboBoxSelRede.removeAllItems();
        this.jComboBoxRemover.removeAllItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneLerEscrever = new javax.swing.JTabbedPane();
        jPanelCriar = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanelRedeEletrica = new javax.swing.JPanel();
        jLabelNameRede = new javax.swing.JLabel();
        jLabelAlimentacaoRede = new javax.swing.JLabel();
        jLabelRedeID = new javax.swing.JLabel();
        jTextFieldNomeRede = new javax.swing.JTextField();
        jTextFieldAlimRede = new javax.swing.JTextField();
        jTextFieldIdRede = new javax.swing.JTextField();
        jButtonInserirContador = new javax.swing.JButton();
        jComboBoxInsRemCont = new javax.swing.JComboBox<>();
        jButtonRemContador = new javax.swing.JButton();
        jButtonInserirFonte = new javax.swing.JButton();
        jButtonRemFonte = new javax.swing.JButton();
        jComboBoxInsRemFonte = new javax.swing.JComboBox<>();
        jButtonCriarRede = new javax.swing.JButton();
        jPanelFonteEnergiaG = new javax.swing.JPanel();
        jLabelTipoFonte = new javax.swing.JLabel();
        jLabelenergiaFonte = new javax.swing.JLabel();
        jLabelIdFonte = new javax.swing.JLabel();
        jTextFieldTipoFonte = new javax.swing.JTextField();
        jTextFieldEnergiaFonte = new javax.swing.JTextField();
        jTextFieldIdFonte = new javax.swing.JTextField();
        jComboBoxSelRede = new javax.swing.JComboBox<>();
        jButtonCriarFonteG = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanelMoradia = new javax.swing.JPanel();
        jLabelProprietario = new javax.swing.JLabel();
        jLabelMorada = new javax.swing.JLabel();
        jLabelLocalidade = new javax.swing.JLabel();
        jLabelCodigoPostal = new javax.swing.JLabel();
        jLabelAutonoma = new javax.swing.JLabel();
        jButtonSimAutonoma = new javax.swing.JButton();
        jButtonNaoAutonoma = new javax.swing.JButton();
        jTextFieldProprietario = new javax.swing.JTextField();
        jTextFieldMorada = new javax.swing.JTextField();
        jTextFieldLocalidade = new javax.swing.JTextField();
        jTextFieldCodigoPostal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButtonCriarMoradia = new javax.swing.JButton();
        jPanelContador = new javax.swing.JPanel();
        jPanelEquipamento = new javax.swing.JPanel();
        jPanelFonteEnergiaP = new javax.swing.JPanel();
        jPanelHistoricoConsumo = new javax.swing.JPanel();
        jPanelEditar = new javax.swing.JPanel();
        jPanelListar = new javax.swing.JPanel();
        jPanelInOut = new javax.swing.JPanel();
        jButtonCarregar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanelGrafo = new javax.swing.JPanel();
        jButtonCriarGrafo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaGrafo = new javax.swing.JTextArea();
        jComboBoxMoradias = new javax.swing.JComboBox<>();
        jLabelVetices = new javax.swing.JLabel();
        jButtonAdicionarM = new javax.swing.JButton();
        jLabelArestas = new javax.swing.JLabel();
        jComboBoxVOrigem = new javax.swing.JComboBox<>();
        jLabelPara = new javax.swing.JLabel();
        jComboBoxVDestino = new javax.swing.JComboBox<>();
        jButtonAdicionarA = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jComboBoxFontes = new javax.swing.JComboBox<>();
        jButtonAdicionarF = new javax.swing.JButton();
        jPanelRemove = new javax.swing.JPanel();
        jComboBoxRemover = new javax.swing.JComboBox<>();
        jButtonRemover = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaRemover = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPaneLerEscrever.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPaneLerEscreverStateChanged(evt);
            }
        });

        jLabelNameRede.setText("Nome:");

        jLabelAlimentacaoRede.setText("Alimentação:");

        jLabelRedeID.setText("ID:");

        jButtonInserirContador.setText("Inserir Contador:");

        jComboBoxInsRemCont.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonRemContador.setText("Remover contador:");

        jButtonInserirFonte.setText("Inserir Fonte Energia:");

        jButtonRemFonte.setText("Remover Fonte Energia:");
        jButtonRemFonte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemFonteActionPerformed(evt);
            }
        });

        jComboBoxInsRemFonte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonCriarRede.setText("Criar");
        jButtonCriarRede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriarRedeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRedeEletricaLayout = new javax.swing.GroupLayout(jPanelRedeEletrica);
        jPanelRedeEletrica.setLayout(jPanelRedeEletricaLayout);
        jPanelRedeEletricaLayout.setHorizontalGroup(
            jPanelRedeEletricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRedeEletricaLayout.createSequentialGroup()
                .addGroup(jPanelRedeEletricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRedeEletricaLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanelRedeEletricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelRedeEletricaLayout.createSequentialGroup()
                                .addGroup(jPanelRedeEletricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNameRede)
                                    .addComponent(jLabelAlimentacaoRede)
                                    .addComponent(jLabelRedeID))
                                .addGap(52, 52, 52)
                                .addGroup(jPanelRedeEletricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldNomeRede)
                                    .addComponent(jTextFieldAlimRede)
                                    .addComponent(jTextFieldIdRede, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                            .addGroup(jPanelRedeEletricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBoxInsRemCont, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRedeEletricaLayout.createSequentialGroup()
                                    .addComponent(jButtonInserirContador)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonRemContador))))
                        .addGap(26, 26, 26)
                        .addComponent(jButtonCriarRede))
                    .addGroup(jPanelRedeEletricaLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jButtonInserirFonte)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRemFonte))
                    .addGroup(jPanelRedeEletricaLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jComboBoxInsRemFonte, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanelRedeEletricaLayout.setVerticalGroup(
            jPanelRedeEletricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRedeEletricaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanelRedeEletricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNameRede)
                    .addComponent(jTextFieldNomeRede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanelRedeEletricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAlimentacaoRede)
                    .addComponent(jTextFieldAlimRede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCriarRede))
                .addGap(32, 32, 32)
                .addGroup(jPanelRedeEletricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelRedeID)
                    .addComponent(jTextFieldIdRede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanelRedeEletricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInserirContador)
                    .addComponent(jButtonRemContador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxInsRemCont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanelRedeEletricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInserirFonte)
                    .addComponent(jButtonRemFonte))
                .addGap(18, 18, 18)
                .addComponent(jComboBoxInsRemFonte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("RedeEletrica", jPanelRedeEletrica);

        jLabelTipoFonte.setText("Tipo:");

        jLabelenergiaFonte.setText("Energia produzida:");

        jLabelIdFonte.setText("ID:");

        jComboBoxSelRede.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonCriarFonteG.setText("Criar");
        jButtonCriarFonteG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriarFonteGActionPerformed(evt);
            }
        });

        jLabel1.setText("Rede:");

        javax.swing.GroupLayout jPanelFonteEnergiaGLayout = new javax.swing.GroupLayout(jPanelFonteEnergiaG);
        jPanelFonteEnergiaG.setLayout(jPanelFonteEnergiaGLayout);
        jPanelFonteEnergiaGLayout.setHorizontalGroup(
            jPanelFonteEnergiaGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFonteEnergiaGLayout.createSequentialGroup()
                .addGroup(jPanelFonteEnergiaGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFonteEnergiaGLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jButtonCriarFonteG))
                    .addGroup(jPanelFonteEnergiaGLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanelFonteEnergiaGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFonteEnergiaGLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(94, 94, 94)
                                .addComponent(jComboBoxSelRede, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelFonteEnergiaGLayout.createSequentialGroup()
                                .addGroup(jPanelFonteEnergiaGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTipoFonte)
                                    .addComponent(jLabelenergiaFonte)
                                    .addComponent(jLabelIdFonte))
                                .addGap(20, 20, 20)
                                .addGroup(jPanelFonteEnergiaGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldTipoFonte)
                                    .addComponent(jTextFieldEnergiaFonte)
                                    .addComponent(jTextFieldIdFonte, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        jPanelFonteEnergiaGLayout.setVerticalGroup(
            jPanelFonteEnergiaGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFonteEnergiaGLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanelFonteEnergiaGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoFonte)
                    .addComponent(jTextFieldTipoFonte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanelFonteEnergiaGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelenergiaFonte)
                    .addComponent(jTextFieldEnergiaFonte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanelFonteEnergiaGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelIdFonte)
                    .addComponent(jTextFieldIdFonte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanelFonteEnergiaGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSelRede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jButtonCriarFonteG)
                .addContainerGap(263, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("FonteEnergiaG", jPanelFonteEnergiaG);

        jLabelProprietario.setText("Proprietario:");

        jLabelMorada.setText("Morada:");

        jLabelLocalidade.setText("Localidade:");

        jLabelCodigoPostal.setText("Codigo Postal:");

        jLabelAutonoma.setText("Autonoma?");

        jButtonSimAutonoma.setText("Sim");

        jButtonNaoAutonoma.setText("Não");

        jButton1.setText("Inserir Equipamento:");

        jButton2.setText("Remover Equipamento:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton3.setText("Inserir Painel Solar:");

        jButton4.setText("Remover Painel Solar:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonCriarMoradia.setText("Criar");
        jButtonCriarMoradia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriarMoradiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMoradiaLayout = new javax.swing.GroupLayout(jPanelMoradia);
        jPanelMoradia.setLayout(jPanelMoradiaLayout);
        jPanelMoradiaLayout.setHorizontalGroup(
            jPanelMoradiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMoradiaLayout.createSequentialGroup()
                .addGroup(jPanelMoradiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMoradiaLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanelMoradiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelMoradiaLayout.createSequentialGroup()
                                .addComponent(jLabelAutonoma)
                                .addGap(66, 66, 66)
                                .addComponent(jButtonSimAutonoma)
                                .addGap(46, 46, 46)
                                .addComponent(jButtonNaoAutonoma))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMoradiaLayout.createSequentialGroup()
                                .addGroup(jPanelMoradiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelProprietario)
                                    .addComponent(jLabelMorada)
                                    .addComponent(jLabelLocalidade)
                                    .addComponent(jLabelCodigoPostal))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelMoradiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldProprietario, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addComponent(jTextFieldMorada)
                                    .addComponent(jTextFieldLocalidade)
                                    .addComponent(jTextFieldCodigoPostal))))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCriarMoradia))
                    .addGroup(jPanelMoradiaLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMoradiaLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addGroup(jPanelMoradiaLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(jPanelMoradiaLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanelMoradiaLayout.setVerticalGroup(
            jPanelMoradiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMoradiaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanelMoradiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelMoradiaLayout.createSequentialGroup()
                        .addGroup(jPanelMoradiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelMoradiaLayout.createSequentialGroup()
                                .addGroup(jPanelMoradiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelProprietario)
                                    .addComponent(jTextFieldProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addComponent(jLabelMorada))
                            .addComponent(jTextFieldMorada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jLabelLocalidade))
                    .addComponent(jTextFieldLocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCriarMoradia))
                .addGap(23, 23, 23)
                .addGroup(jPanelMoradiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelCodigoPostal)
                    .addComponent(jTextFieldCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanelMoradiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAutonoma)
                    .addComponent(jButtonSimAutonoma)
                    .addComponent(jButtonNaoAutonoma))
                .addGap(37, 37, 37)
                .addGroup(jPanelMoradiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMoradiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Moradia", jPanelMoradia);

        jPanelContador.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        javax.swing.GroupLayout jPanelContadorLayout = new javax.swing.GroupLayout(jPanelContador);
        jPanelContador.setLayout(jPanelContadorLayout);
        jPanelContadorLayout.setHorizontalGroup(
            jPanelContadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
        );
        jPanelContadorLayout.setVerticalGroup(
            jPanelContadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Contador", jPanelContador);

        javax.swing.GroupLayout jPanelEquipamentoLayout = new javax.swing.GroupLayout(jPanelEquipamento);
        jPanelEquipamento.setLayout(jPanelEquipamentoLayout);
        jPanelEquipamentoLayout.setHorizontalGroup(
            jPanelEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
        );
        jPanelEquipamentoLayout.setVerticalGroup(
            jPanelEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Equipamento", jPanelEquipamento);

        javax.swing.GroupLayout jPanelFonteEnergiaPLayout = new javax.swing.GroupLayout(jPanelFonteEnergiaP);
        jPanelFonteEnergiaP.setLayout(jPanelFonteEnergiaPLayout);
        jPanelFonteEnergiaPLayout.setHorizontalGroup(
            jPanelFonteEnergiaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
        );
        jPanelFonteEnergiaPLayout.setVerticalGroup(
            jPanelFonteEnergiaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("FonteEnergiaP", jPanelFonteEnergiaP);

        javax.swing.GroupLayout jPanelHistoricoConsumoLayout = new javax.swing.GroupLayout(jPanelHistoricoConsumo);
        jPanelHistoricoConsumo.setLayout(jPanelHistoricoConsumoLayout);
        jPanelHistoricoConsumoLayout.setHorizontalGroup(
            jPanelHistoricoConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
        );
        jPanelHistoricoConsumoLayout.setVerticalGroup(
            jPanelHistoricoConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("HistoricoConsumo", jPanelHistoricoConsumo);

        javax.swing.GroupLayout jPanelCriarLayout = new javax.swing.GroupLayout(jPanelCriar);
        jPanelCriar.setLayout(jPanelCriarLayout);
        jPanelCriarLayout.setHorizontalGroup(
            jPanelCriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCriarLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jPanelCriarLayout.setVerticalGroup(
            jPanelCriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCriarLayout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneLerEscrever.addTab("Criar", jPanelCriar);

        javax.swing.GroupLayout jPanelEditarLayout = new javax.swing.GroupLayout(jPanelEditar);
        jPanelEditar.setLayout(jPanelEditarLayout);
        jPanelEditarLayout.setHorizontalGroup(
            jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
        );
        jPanelEditarLayout.setVerticalGroup(
            jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jTabbedPaneLerEscrever.addTab("Editar", jPanelEditar);

        javax.swing.GroupLayout jPanelListarLayout = new javax.swing.GroupLayout(jPanelListar);
        jPanelListar.setLayout(jPanelListarLayout);
        jPanelListarLayout.setHorizontalGroup(
            jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
        );
        jPanelListarLayout.setVerticalGroup(
            jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jTabbedPaneLerEscrever.addTab("Listar", jPanelListar);

        jButtonCarregar.setText("Carregar");
        jButtonCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarregarActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanelInOutLayout = new javax.swing.GroupLayout(jPanelInOut);
        jPanelInOut.setLayout(jPanelInOutLayout);
        jPanelInOutLayout.setHorizontalGroup(
            jPanelInOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInOutLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(jPanelInOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCarregar))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPanelInOutLayout.setVerticalGroup(
            jPanelInOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInOutLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jButtonCarregar)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(294, Short.MAX_VALUE))
        );

        jTabbedPaneLerEscrever.addTab("Ler/Escrever", jPanelInOut);

        jPanelGrafo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelGrafoMouseClicked(evt);
            }
        });

        jButtonCriarGrafo.setText("Criar Grafo");
        jButtonCriarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriarGrafoActionPerformed(evt);
            }
        });

        jTextAreaGrafo.setEditable(false);
        jTextAreaGrafo.setColumns(20);
        jTextAreaGrafo.setRows(5);
        jScrollPane1.setViewportView(jTextAreaGrafo);

        jComboBoxMoradias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxMoradias.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxMoradiasItemStateChanged(evt);
            }
        });
        jComboBoxMoradias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMoradiasActionPerformed(evt);
            }
        });

        jLabelVetices.setText("Vertices:");

        jButtonAdicionarM.setText("Adicionar");
        jButtonAdicionarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarMActionPerformed(evt);
            }
        });

        jLabelArestas.setText("Arestas:");

        jComboBoxVOrigem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelPara.setText("para");

        jComboBoxVDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonAdicionarA.setText("Adicionar");
        jButtonAdicionarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarAActionPerformed(evt);
            }
        });

        jComboBoxFontes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonAdicionarF.setText("Adicionar");
        jButtonAdicionarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelGrafoLayout = new javax.swing.GroupLayout(jPanelGrafo);
        jPanelGrafo.setLayout(jPanelGrafoLayout);
        jPanelGrafoLayout.setHorizontalGroup(
            jPanelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGrafoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGrafoLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButtonCriarGrafo)
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelGrafoLayout.createSequentialGroup()
                        .addComponent(jLabelVetices)
                        .addGap(59, 59, 59)
                        .addGroup(jPanelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelGrafoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jComboBoxFontes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jComboBoxMoradias, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonAdicionarM)
                            .addComponent(jButtonAdicionarF))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGrafoLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelArestas)
                    .addGroup(jPanelGrafoLayout.createSequentialGroup()
                        .addComponent(jComboBoxVOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPara)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxVDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAdicionarA)))
                .addGap(15, 15, 15))
        );
        jPanelGrafoLayout.setVerticalGroup(
            jPanelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGrafoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelVetices)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxMoradias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdicionarM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxFontes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdicionarF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jLabelArestas)
                .addGap(18, 18, 18)
                .addGroup(jPanelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdicionarA)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxVDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPara)
                    .addComponent(jComboBoxVOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGrafoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGrafoLayout.createSequentialGroup()
                        .addComponent(jButtonCriarGrafo)
                        .addGap(224, 224, 224))))
        );

        jTabbedPaneLerEscrever.addTab("Grafo", jPanelGrafo);

        jPanelRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelRemoveMouseClicked(evt);
            }
        });

        jComboBoxRemover.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonRemover.setText("Remover");
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });

        jTextAreaRemover.setEditable(false);
        jTextAreaRemover.setColumns(20);
        jTextAreaRemover.setRows(5);
        jScrollPane2.setViewportView(jTextAreaRemover);

        javax.swing.GroupLayout jPanelRemoveLayout = new javax.swing.GroupLayout(jPanelRemove);
        jPanelRemove.setLayout(jPanelRemoveLayout);
        jPanelRemoveLayout.setHorizontalGroup(
            jPanelRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRemoveLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(jPanelRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelRemoveLayout.createSequentialGroup()
                        .addComponent(jComboBoxRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jButtonRemover)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanelRemoveLayout.setVerticalGroup(
            jPanelRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRemoveLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanelRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxRemover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRemover))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(298, Short.MAX_VALUE))
        );

        jTabbedPaneLerEscrever.addTab("Remover", jPanelRemove);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneLerEscrever)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneLerEscrever)
                .addContainerGap())
        );

        jTabbedPaneLerEscrever.getAccessibleContext().setAccessibleName("Editar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRemFonteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemFonteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRemFonteActionPerformed

    private void jButtonCriarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriarGrafoActionPerformed
        this.jComboBoxMoradias.setVisible(true);
        this.jComboBoxMoradias.setVisible(true);
        this.jComboBoxMoradias.addItem("Dikstra");
    }//GEN-LAST:event_jButtonCriarGrafoActionPerformed

    private void jComboBoxMoradiasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxMoradiasItemStateChanged
        
    }//GEN-LAST:event_jComboBoxMoradiasItemStateChanged
/**
 * Cria uma nova RedeEletrica e adiciona ao ArrayList de redes que já foram criadas.
 * @param evt 
 */
    private void jButtonCriarRedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriarRedeActionPerformed
        int auxID = Integer.parseInt(this.jTextFieldIdRede.getText());
        double auxAlim = Double.parseDouble(this.jTextFieldAlimRede.getText());
        RedeEletrica rede = new RedeEletrica(this.jTextFieldNomeRede.getText(),auxAlim,auxID);
        redes.add(rede);
        this.jButtonInserirContador.setVisible(true);
        this.jButtonRemContador.setVisible(true);
        this.jButtonInserirFonte.setVisible(true);
        this.jButtonRemFonte.setVisible(true);
        this.jComboBoxInsRemCont.setVisible(true);
        this.jComboBoxInsRemFonte.setVisible(true);
        this.jTextFieldAlimRede.setText("");
        this.jTextFieldIdRede.setText("");
        this.jTextFieldNomeRede.setText("");
        this.jComboBoxSelRede.addItem(rede.getNome());
    }//GEN-LAST:event_jButtonCriarRedeActionPerformed
/**
 * Cria uma nova FonteEnergiaG e adiciona ao ArrayList de fontes que já foram criadas.
 * @param evt 
 */
    private void jButtonCriarFonteGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriarFonteGActionPerformed
        int auxID = Integer.parseInt(this.jTextFieldIdFonte.getText());
        double auxEnergia = Double.parseDouble(this.jTextFieldEnergiaFonte.getText());
        RedeEletrica r=null;
        for(RedeEletrica ri : redes)
                if(ri.getNome().compareTo(this.jComboBoxSelRede.getSelectedItem().toString())==0)
                    r=ri;
        FonteEnergiaG fonte = new FonteEnergiaG(this.jTextFieldTipoFonte.getText(),auxEnergia,auxID);
        if(r!=null)
            fonte.setRede(r);
        this.fontes.add(fonte);
        System.out.println(fonte.toString());
        
    }//GEN-LAST:event_jButtonCriarFonteGActionPerformed

    private void jComboBoxMoradiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMoradiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMoradiasActionPerformed
/**
 * Adicionar ao grafo um NoMoradia.
 * @param evt 
 */
    private void jButtonAdicionarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarMActionPerformed
        String sM[]= this.jComboBoxMoradias.getSelectedItem().toString().split("-");
        int auxM = Integer.parseInt(sM[0]);
        for(Moradia m :this.moradias){
            if(auxM == m.hashCode()){
                NoMoradia n = new NoMoradia(m);
                this.grafo.addNode(n);
                this.jComboBoxVDestino.addItem(m.hashCode()+"-"+m.toString());
                this.jComboBoxVOrigem.addItem(m.hashCode()+"-"+m.toString());
            }
        }
    }//GEN-LAST:event_jButtonAdicionarMActionPerformed

    private void jButtonAdicionarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAdicionarAActionPerformed
/**
 * Quando se carrega no painel grafo restaura-se todo o conteúdo nas comboBox com os possiveis nós do grafo.
 * @param evt 
 */
    private void jPanelGrafoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGrafoMouseClicked
        this.jComboBoxVDestino.removeAllItems();
        this.jComboBoxVOrigem.removeAllItems();
        this.jComboBoxMoradias.removeAllItems();
        this.jComboBoxFontes.removeAllItems();
        for(Moradia m : this.moradias){
            this.jComboBoxMoradias.addItem(m.hashCode()+"-"+m.toString());
        }
        for(FonteEnergiaG f : this.fontes){
            this.jComboBoxFontes.addItem(f.hashCode()+"-"+f.toString());
        }
    }//GEN-LAST:event_jPanelGrafoMouseClicked
/**
 * Adicionar ao grafo um NoFonteEnergia.
 * @param evt 
 */
    private void jButtonAdicionarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarFActionPerformed
        String sF[]= this.jComboBoxFontes.getSelectedItem().toString().split("-");
        int auxF = Integer.parseInt(sF[0]);
        for(FonteEnergiaG f :this.fontes){
            if(auxF == f.hashCode()){
                NoFonteEnergia n = new NoFonteEnergia(f);
                this.grafo.addNode(n);
                this.jComboBoxVDestino.addItem(f.hashCode()+"-"+f.toString());
                this.jComboBoxVOrigem.addItem(f.hashCode()+"-"+f.toString());
            }
        }
    }//GEN-LAST:event_jButtonAdicionarFActionPerformed
/**
 * Remove do grafo o nó selecionado na ComboBox.
 * @param evt 
 */
    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed
        String s[] = this.jComboBoxRemover.getSelectedItem().toString().split("-");
        int aux = Integer.parseInt(s[0]);
        this.jComboBoxRemover.removeItemAt(this.jComboBoxRemover.getSelectedIndex());
        GrafoDirigido subG = new GrafoDirigido(grafo.V());
        for(NoMoradia gi : grafo.getNodesM()){
            if(gi.getId()!= aux){
                subG.addNode(gi);
            }
        }
        for(NoFonteEnergia gi : grafo.getNodesF()){
            if(gi.getId()!= aux){
                subG.addNode(gi);
            } 
        }
        for(FlowEdge di: this.grafo.edges())
            if(subG.pertenceGrafo(di.from())==true && subG.pertenceGrafo(di.to())==true){
                subG.addEdge(di);
            } 
        this.grafo = subG;
        this.jTextAreaRemover.setText(subG.toString());
    }//GEN-LAST:event_jButtonRemoverActionPerformed
/**
 * Quando se carrega no painel Remover restaura-se todo o conteúdo na comboBox com os nós do grafo.
 * @param evt 
 */
    private void jPanelRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRemoveMouseClicked
        this.jComboBoxRemover.removeAllItems();
        for(NoMoradia m : this.grafo.getNodesM()){
            this.jComboBoxRemover.addItem(m.getId()+"-"+m.getM().toString());
        }
        for(NoFonteEnergia f : this.grafo.getNodesF()){
            this.jComboBoxRemover.addItem(f.getId()+"-"+f.getFonte().toString());
        }
    }//GEN-LAST:event_jPanelRemoveMouseClicked
/**
 * Carrega o grafo guardado em ficheiro binário e imprime na textArea
 * @param evt 
 */
    private void jButtonCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarregarActionPerformed
        try {
            this.lerGrafoBin();
            this.jTextArea1.setText(grafo.toString());
        } catch (IOException ex) {
            Logger.getLogger(InterfaceGrafic.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InterfaceGrafic.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCarregarActionPerformed
/**
 * Restaura os items das ComboBox do painel grafo com o do grafo que foi carregado.
 * @param evt 
 */
    private void jTabbedPaneLerEscreverStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPaneLerEscreverStateChanged
        this.jComboBoxVDestino.removeAllItems();
        this.jComboBoxVOrigem.removeAllItems();
        this.jComboBoxMoradias.removeAllItems();
        this.jComboBoxFontes.removeAllItems();
        for(Moradia m : this.moradias){
            this.jComboBoxMoradias.addItem(m.hashCode()+"-"+m.toString());
        }
        for(FonteEnergiaG f : this.fontes){
            this.jComboBoxFontes.addItem(f.hashCode()+"-"+f.toString());
        }
    }//GEN-LAST:event_jTabbedPaneLerEscreverStateChanged

    private void jButtonCriarMoradiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriarMoradiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCriarMoradiaActionPerformed
/**
 * Função para ler o grafo guardado em ficheiro binário.
 * @throws FileNotFoundException
 * @throws IOException
 * @throws ClassNotFoundException 
 */
    public void lerGrafoBin() throws FileNotFoundException, IOException, ClassNotFoundException{//  Lê o grafo do ficheiro binario para ser utilizado
        String filename = ".//data//GrafoDirigidoBin.bin";
        File f = new File(filename);
        FileInputStream fis = new FileInputStream(f);
        ObjectInputStream ois = new ObjectInputStream(fis);
        this.grafo = (GrafoDirigido)ois.readObject();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceGrafic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonAdicionarA;
    private javax.swing.JButton jButtonAdicionarF;
    private javax.swing.JButton jButtonAdicionarM;
    private javax.swing.JButton jButtonCarregar;
    private javax.swing.JButton jButtonCriarFonteG;
    private javax.swing.JButton jButtonCriarGrafo;
    private javax.swing.JButton jButtonCriarMoradia;
    private javax.swing.JButton jButtonCriarRede;
    private javax.swing.JButton jButtonInserirContador;
    private javax.swing.JButton jButtonInserirFonte;
    private javax.swing.JButton jButtonNaoAutonoma;
    private javax.swing.JButton jButtonRemContador;
    private javax.swing.JButton jButtonRemFonte;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JButton jButtonSimAutonoma;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBoxFontes;
    private javax.swing.JComboBox<String> jComboBoxInsRemCont;
    private javax.swing.JComboBox<String> jComboBoxInsRemFonte;
    private javax.swing.JComboBox<String> jComboBoxMoradias;
    private javax.swing.JComboBox<String> jComboBoxRemover;
    private javax.swing.JComboBox<String> jComboBoxSelRede;
    private javax.swing.JComboBox<String> jComboBoxVDestino;
    private javax.swing.JComboBox<String> jComboBoxVOrigem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAlimentacaoRede;
    private javax.swing.JLabel jLabelArestas;
    private javax.swing.JLabel jLabelAutonoma;
    private javax.swing.JLabel jLabelCodigoPostal;
    private javax.swing.JLabel jLabelIdFonte;
    private javax.swing.JLabel jLabelLocalidade;
    private javax.swing.JLabel jLabelMorada;
    private javax.swing.JLabel jLabelNameRede;
    private javax.swing.JLabel jLabelPara;
    private javax.swing.JLabel jLabelProprietario;
    private javax.swing.JLabel jLabelRedeID;
    private javax.swing.JLabel jLabelTipoFonte;
    private javax.swing.JLabel jLabelVetices;
    private javax.swing.JLabel jLabelenergiaFonte;
    private javax.swing.JPanel jPanelContador;
    private javax.swing.JPanel jPanelCriar;
    private javax.swing.JPanel jPanelEditar;
    private javax.swing.JPanel jPanelEquipamento;
    private javax.swing.JPanel jPanelFonteEnergiaG;
    private javax.swing.JPanel jPanelFonteEnergiaP;
    private javax.swing.JPanel jPanelGrafo;
    private javax.swing.JPanel jPanelHistoricoConsumo;
    private javax.swing.JPanel jPanelInOut;
    private javax.swing.JPanel jPanelListar;
    private javax.swing.JPanel jPanelMoradia;
    private javax.swing.JPanel jPanelRedeEletrica;
    private javax.swing.JPanel jPanelRemove;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPaneLerEscrever;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextAreaGrafo;
    private javax.swing.JTextArea jTextAreaRemover;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldAlimRede;
    private javax.swing.JTextField jTextFieldCodigoPostal;
    private javax.swing.JTextField jTextFieldEnergiaFonte;
    private javax.swing.JTextField jTextFieldIdFonte;
    private javax.swing.JTextField jTextFieldIdRede;
    private javax.swing.JTextField jTextFieldLocalidade;
    private javax.swing.JTextField jTextFieldMorada;
    private javax.swing.JTextField jTextFieldNomeRede;
    private javax.swing.JTextField jTextFieldProprietario;
    private javax.swing.JTextField jTextFieldTipoFonte;
    // End of variables declaration//GEN-END:variables
}
