/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetofinal_aed2_lp2;

import edu.princeton.cs.algs4.BellmanFordSP;
import edu.princeton.cs.algs4.DepthFirstOrder;
import edu.princeton.cs.algs4.DirectedEdge;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import projetofinal_aed2_lp2.aux.GrafoDirigido;
import projetofinal_aed2_lp2.aux.NoFonteEnergia;
import projetofinal_aed2_lp2.aux.NoMoradia;
import edu.princeton.cs.algs4.DijkstraSP;
import edu.princeton.cs.algs4.EdgeWeightedDigraph;
import edu.princeton.cs.algs4.FlowEdge;
import edu.princeton.cs.algs4.FordFulkerson;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JButton;

/**
 *
 * @author patricia
 */
public class interfaceGrafica extends javax.swing.JFrame {
    
    private static GrafoDirigido g = new GrafoDirigido(15);
    
    private static GrafoDirigido subGAux=new GrafoDirigido(15);// vai ser usada para ir inserindo o sub Grafo
    
    private static GrafoDirigido subG=new GrafoDirigido(15);// subGrafo final que se pode usar em outras funções
    
    /**
     * Creates new form interfaceGrafica
     * Define alguns componentes como invisiveis e adiciona items ás ComboBox.
     */
    public interfaceGrafica() throws IOException, FileNotFoundException, ClassNotFoundException {
        initComponents();
        this.lerGrafoBin();
        this.iniciarJComboBox();
        this.jComboBoxBellmanFordSP.setVisible(false);
        this.jTextAreaBellmanFordSP.setVisible(false);
        this.jButtonResultadoBellmanFordSP.setVisible(false);
        this.jLabelOrigemBellmanFordSP.setVisible(false);
        this.jScrollPane6.setVisible(false);
        this.jButtonResultadoDijkstra.setVisible(false);
        this.jTextAreaDijkstra.setVisible(false);
        this.jComboBoxDDestino.setVisible(false);
        this.jComboBoxDOrigem.setVisible(false);
        this.jLabelDDestino.setVisible(false);
        this.jLabelDOrigem.setVisible(false);
        this.jScrollPane1.setVisible(false);
        this.jComboBoxA.removeAllItems();
        this.jComboBoxA.addItem(">");
        this.jComboBoxA.addItem("<");
        this.jTextAreaGrafo.setText(g.toString());
        this.jButtonResultadoFordFulkerson.setVisible(false);
        this.jTextAreaFordFulkerson.setVisible(false);
        this.jComboBoxDestinoFordFulkerson.setVisible(false);
        this.jComboBoxOrigemFordFulkerson.setVisible(false);
        this.jLabelDestinoFordFulkerson.setVisible(false);
        this.jLabelOrigemFordFulkerson.setVisible(false);
        this.jScrollPane11.setVisible(false);
        this.jButtonSubGrafoFordFulkerson.setVisible(true);
    }
    /**
     * Inicia a comboBox do sub grafo com os nós do grafo.
     */
    public void iniciarJComboBox(){
        this.jComboBoxSubGrafo.removeAllItems();
        for(NoMoradia gi : g.getNodesM()){
            this.jComboBoxSubGrafo.addItem(gi.getId()+ "-"+gi.getM().toString());
        }
        for(NoFonteEnergia gi : g.getNodesF()){
            this.jComboBoxSubGrafo.addItem(gi.getId()+ "-"+gi.getFonte().toString());
        }
    }
/**
 * Função para ler o grafo guardado em ficheiro binário.
 * @throws FileNotFoundException
 * @throws IOException
 * @throws ClassNotFoundException 
 */
    public void lerGrafoBin() throws FileNotFoundException, IOException, ClassNotFoundException{//  Lê o grafo do ficheiro binario para ser utilizado
        String filename = ".//data//GrafoDirigidoBin.bin";
        File f = new File(filename);
        FileInputStream fis = new FileInputStream(f);
        ObjectInputStream ois = new ObjectInputStream(fis);
        this.g = (GrafoDirigido)ois.readObject();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelGrafo = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextAreaGrafo = new javax.swing.JTextArea();
        jPanelSubGrafo = new javax.swing.JPanel();
        jComboBoxSubGrafo = new javax.swing.JComboBox<>();
        jButtonSubGrafoInserir = new javax.swing.JButton();
        jButtonSubGrafoFinalizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaSubGrafo = new javax.swing.JTextArea();
        jPanelDijkstra = new javax.swing.JPanel();
        jLabelDOrigem = new javax.swing.JLabel();
        jLabelDDestino = new javax.swing.JLabel();
        jComboBoxDOrigem = new javax.swing.JComboBox<>();
        jComboBoxDDestino = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDijkstra = new javax.swing.JTextArea();
        jButtonResultadoDijkstra = new javax.swing.JButton();
        jButtonGrafoDijkstra = new javax.swing.JButton();
        jButtonSubGrafoDijkstra = new javax.swing.JButton();
        jPanelDFS = new javax.swing.JPanel();
        jButtonGrafoDFS = new javax.swing.JButton();
        jButtonDubGrafoDFS = new javax.swing.JButton();
        jLabelPosOrdem = new javax.swing.JLabel();
        jLabelPreOrdem = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaPosOrdem = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaPreOrdem = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaPosOrdemInv = new javax.swing.JTextArea();
        jLabelPosOrdemInv = new javax.swing.JLabel();
        jPanelBellmanFord = new javax.swing.JPanel();
        jComboBoxBellmanFordSP = new javax.swing.JComboBox<>();
        jLabelOrigemBellmanFordSP = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextAreaBellmanFordSP = new javax.swing.JTextArea();
        jButtonGrafoBellmanFordSP = new javax.swing.JButton();
        jButtonSubGrafoBellmanFordSP = new javax.swing.JButton();
        jButtonResultadoBellmanFordSP = new javax.swing.JButton();
        jPanelEstatisticas = new javax.swing.JPanel();
        jLabelAEst = new javax.swing.JLabel();
        jButtonSubGrafoEstatisticas = new javax.swing.JButton();
        jButtonGrafoEstatisticas = new javax.swing.JButton();
        jComboBoxA = new javax.swing.JComboBox<>();
        jLabelConEsta = new javax.swing.JLabel();
        jTextFieldBDiaHora = new javax.swing.JTextField();
        jLabelBEsta = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextAreaB = new javax.swing.JTextArea();
        jButtonObterA = new javax.swing.JButton();
        jButtonObterB = new javax.swing.JButton();
        jLabelCEsta = new javax.swing.JLabel();
        jButtonObterC = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextAreaC = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextAreaA = new javax.swing.JTextArea();
        jPanelFordFulkerson = new javax.swing.JPanel();
        jButtonGrafoFordFulkerson = new javax.swing.JButton();
        jButtonSubGrafoFordFulkerson = new javax.swing.JButton();
        jLabelOrigemFordFulkerson = new javax.swing.JLabel();
        jComboBoxOrigemFordFulkerson = new javax.swing.JComboBox<>();
        jLabelDestinoFordFulkerson = new javax.swing.JLabel();
        jComboBoxDestinoFordFulkerson = new javax.swing.JComboBox<>();
        jButtonResultadoFordFulkerson = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextAreaFordFulkerson = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jTextAreaGrafo.setEditable(false);
        jTextAreaGrafo.setColumns(20);
        jTextAreaGrafo.setRows(5);
        jScrollPane10.setViewportView(jTextAreaGrafo);

        javax.swing.GroupLayout jPanelGrafoLayout = new javax.swing.GroupLayout(jPanelGrafo);
        jPanelGrafo.setLayout(jPanelGrafoLayout);
        jPanelGrafoLayout.setHorizontalGroup(
            jPanelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGrafoLayout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(349, Short.MAX_VALUE))
        );
        jPanelGrafoLayout.setVerticalGroup(
            jPanelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGrafoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Grafo", jPanelGrafo);

        jComboBoxSubGrafo.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jComboBoxSubGrafo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxSubGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSubGrafoActionPerformed(evt);
            }
        });

        jButtonSubGrafoInserir.setText("Inserir");
        jButtonSubGrafoInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubGrafoInserirActionPerformed(evt);
            }
        });

        jButtonSubGrafoFinalizar.setLabel("Finalizar");
        jButtonSubGrafoFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubGrafoFinalizarActionPerformed(evt);
            }
        });

        jTextAreaSubGrafo.setEditable(false);
        jTextAreaSubGrafo.setColumns(20);
        jTextAreaSubGrafo.setRows(5);
        jScrollPane2.setViewportView(jTextAreaSubGrafo);

        javax.swing.GroupLayout jPanelSubGrafoLayout = new javax.swing.GroupLayout(jPanelSubGrafo);
        jPanelSubGrafo.setLayout(jPanelSubGrafoLayout);
        jPanelSubGrafoLayout.setHorizontalGroup(
            jPanelSubGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSubGrafoLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jComboBoxSubGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSubGrafoInserir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSubGrafoLayout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(jButtonSubGrafoFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(434, 434, 434))
        );
        jPanelSubGrafoLayout.setVerticalGroup(
            jPanelSubGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSubGrafoLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(jPanelSubGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSubGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSubGrafoInserir))
                .addGroup(jPanelSubGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSubGrafoLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jButtonSubGrafoFinalizar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSubGrafoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165))))
        );

        jTabbedPane1.addTab("SubGrafo", jPanelSubGrafo);

        jLabelDOrigem.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabelDOrigem.setText("Origem:");

        jLabelDDestino.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabelDDestino.setText("Destino:");

        jComboBoxDOrigem.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jComboBoxDOrigem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxDDestino.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jComboBoxDDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextAreaDijkstra.setEditable(false);
        jTextAreaDijkstra.setColumns(20);
        jTextAreaDijkstra.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDijkstra);

        jButtonResultadoDijkstra.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButtonResultadoDijkstra.setText("Resultado");
        jButtonResultadoDijkstra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResultadoDijkstraActionPerformed(evt);
            }
        });

        jButtonGrafoDijkstra.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButtonGrafoDijkstra.setText("Grafo");
        jButtonGrafoDijkstra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGrafoDijkstraActionPerformed(evt);
            }
        });

        jButtonSubGrafoDijkstra.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButtonSubGrafoDijkstra.setText("SubGrafo");
        jButtonSubGrafoDijkstra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubGrafoDijkstraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDijkstraLayout = new javax.swing.GroupLayout(jPanelDijkstra);
        jPanelDijkstra.setLayout(jPanelDijkstraLayout);
        jPanelDijkstraLayout.setHorizontalGroup(
            jPanelDijkstraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDijkstraLayout.createSequentialGroup()
                .addGroup(jPanelDijkstraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDijkstraLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDijkstraLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanelDijkstraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelDijkstraLayout.createSequentialGroup()
                                .addGroup(jPanelDijkstraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDDestino)
                                    .addComponent(jLabelDOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68)
                                .addGroup(jPanelDijkstraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBoxDDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxDOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButtonResultadoDijkstra))
                            .addGroup(jPanelDijkstraLayout.createSequentialGroup()
                                .addComponent(jButtonGrafoDijkstra)
                                .addGap(124, 124, 124)
                                .addComponent(jButtonSubGrafoDijkstra)
                                .addGap(122, 122, 122)))))
                .addContainerGap(470, Short.MAX_VALUE))
        );
        jPanelDijkstraLayout.setVerticalGroup(
            jPanelDijkstraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDijkstraLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelDijkstraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGrafoDijkstra)
                    .addComponent(jButtonSubGrafoDijkstra))
                .addGap(18, 18, 18)
                .addGroup(jPanelDijkstraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDijkstraLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanelDijkstraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxDDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDDestino))
                        .addGap(31, 31, 31))
                    .addGroup(jPanelDijkstraLayout.createSequentialGroup()
                        .addGroup(jPanelDijkstraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonResultadoDijkstra)
                            .addComponent(jComboBoxDOrigem)
                            .addComponent(jLabelDOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dijkstra", jPanelDijkstra);

        jButtonGrafoDFS.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButtonGrafoDFS.setText("Grafo");
        jButtonGrafoDFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGrafoDFSActionPerformed(evt);
            }
        });

        jButtonDubGrafoDFS.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButtonDubGrafoDFS.setText("SubGrafo");
        jButtonDubGrafoDFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDubGrafoDFSActionPerformed(evt);
            }
        });

        jLabelPosOrdem.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabelPosOrdem.setText("Pos Ordem:");

        jLabelPreOrdem.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabelPreOrdem.setText("Pre Ordem:");

        jTextAreaPosOrdem.setEditable(false);
        jTextAreaPosOrdem.setColumns(20);
        jTextAreaPosOrdem.setRows(5);
        jScrollPane3.setViewportView(jTextAreaPosOrdem);

        jTextAreaPreOrdem.setEditable(false);
        jTextAreaPreOrdem.setColumns(20);
        jTextAreaPreOrdem.setRows(5);
        jScrollPane4.setViewportView(jTextAreaPreOrdem);

        jTextAreaPosOrdemInv.setEditable(false);
        jTextAreaPosOrdemInv.setColumns(20);
        jTextAreaPosOrdemInv.setRows(5);
        jScrollPane5.setViewportView(jTextAreaPosOrdemInv);

        jLabelPosOrdemInv.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabelPosOrdemInv.setText("Pos Ordem Invertida:");

        javax.swing.GroupLayout jPanelDFSLayout = new javax.swing.GroupLayout(jPanelDFS);
        jPanelDFS.setLayout(jPanelDFSLayout);
        jPanelDFSLayout.setHorizontalGroup(
            jPanelDFSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDFSLayout.createSequentialGroup()
                .addGroup(jPanelDFSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDFSLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jButtonGrafoDFS)
                        .addGap(78, 78, 78)
                        .addComponent(jButtonDubGrafoDFS))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDFSLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDFSLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanelDFSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPosOrdemInv)
                            .addGroup(jPanelDFSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelPreOrdem)
                                .addComponent(jLabelPosOrdem)))
                        .addGap(116, 116, 116)
                        .addGroup(jPanelDFSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(522, Short.MAX_VALUE))
        );
        jPanelDFSLayout.setVerticalGroup(
            jPanelDFSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDFSLayout.createSequentialGroup()
                .addGroup(jPanelDFSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDFSLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDFSLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanelDFSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonGrafoDFS)
                            .addComponent(jButtonDubGrafoDFS))
                        .addGap(73, 73, 73)
                        .addComponent(jLabelPosOrdem)))
                .addGroup(jPanelDFSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDFSLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDFSLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabelPreOrdem)))
                .addGroup(jPanelDFSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDFSLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDFSLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabelPosOrdemInv, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DFS", jPanelDFS);

        jComboBoxBellmanFordSP.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jComboBoxBellmanFordSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelOrigemBellmanFordSP.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabelOrigemBellmanFordSP.setText("Origem:");

        jTextAreaBellmanFordSP.setEditable(false);
        jTextAreaBellmanFordSP.setColumns(20);
        jTextAreaBellmanFordSP.setRows(5);
        jScrollPane6.setViewportView(jTextAreaBellmanFordSP);

        jButtonGrafoBellmanFordSP.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButtonGrafoBellmanFordSP.setText("Grafo");
        jButtonGrafoBellmanFordSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGrafoBellmanFordSPActionPerformed(evt);
            }
        });

        jButtonSubGrafoBellmanFordSP.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButtonSubGrafoBellmanFordSP.setText("SubGrafo");
        jButtonSubGrafoBellmanFordSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubGrafoBellmanFordSPActionPerformed(evt);
            }
        });

        jButtonResultadoBellmanFordSP.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButtonResultadoBellmanFordSP.setText("Resultado");
        jButtonResultadoBellmanFordSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResultadoBellmanFordSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBellmanFordLayout = new javax.swing.GroupLayout(jPanelBellmanFord);
        jPanelBellmanFord.setLayout(jPanelBellmanFordLayout);
        jPanelBellmanFordLayout.setHorizontalGroup(
            jPanelBellmanFordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBellmanFordLayout.createSequentialGroup()
                .addGroup(jPanelBellmanFordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBellmanFordLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jComboBoxBellmanFordSP, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBellmanFordLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jButtonGrafoBellmanFordSP)
                        .addGap(93, 93, 93)
                        .addComponent(jButtonSubGrafoBellmanFordSP))
                    .addGroup(jPanelBellmanFordLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabelOrigemBellmanFordSP))
                    .addGroup(jPanelBellmanFordLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(jButtonResultadoBellmanFordSP)))
                .addGap(39, 400, Short.MAX_VALUE))
        );
        jPanelBellmanFordLayout.setVerticalGroup(
            jPanelBellmanFordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBellmanFordLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelBellmanFordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGrafoBellmanFordSP)
                    .addComponent(jButtonSubGrafoBellmanFordSP))
                .addGap(52, 52, 52)
                .addComponent(jLabelOrigemBellmanFordSP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxBellmanFordSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelBellmanFordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBellmanFordLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBellmanFordLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jButtonResultadoBellmanFordSP)))
                .addContainerGap(182, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("BellmanFord", jPanelBellmanFord);

        jLabelAEst.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabelAEst.setText("a. Moradia");

        jButtonSubGrafoEstatisticas.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButtonSubGrafoEstatisticas.setText("SubGrafo");
        jButtonSubGrafoEstatisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubGrafoEstatisticasActionPerformed(evt);
            }
        });

        jButtonGrafoEstatisticas.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButtonGrafoEstatisticas.setText("Grafo");
        jButtonGrafoEstatisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGrafoEstatisticasActionPerformed(evt);
            }
        });

        jComboBoxA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxA.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxAItemStateChanged(evt);
            }
        });

        jLabelConEsta.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabelConEsta.setText("Consumo");

        jTextFieldBDiaHora.setEditable(false);
        jTextFieldBDiaHora.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        jLabelBEsta.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabelBEsta.setText("b. Moradia com consumo Dia e horas:");

        jTextAreaB.setEditable(false);
        jTextAreaB.setColumns(20);
        jTextAreaB.setRows(5);
        jScrollPane7.setViewportView(jTextAreaB);

        jButtonObterA.setText("Obter");
        jButtonObterA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObterAActionPerformed(evt);
            }
        });

        jButtonObterB.setText("Obter");
        jButtonObterB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObterBActionPerformed(evt);
            }
        });

        jLabelCEsta.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabelCEsta.setText("c. Moradia eficientes");

        jButtonObterC.setText("Obter");
        jButtonObterC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObterCActionPerformed(evt);
            }
        });

        jTextAreaC.setEditable(false);
        jTextAreaC.setColumns(20);
        jTextAreaC.setRows(5);
        jScrollPane8.setViewportView(jTextAreaC);

        jTextAreaA.setEditable(false);
        jTextAreaA.setColumns(20);
        jTextAreaA.setRows(5);
        jScrollPane9.setViewportView(jTextAreaA);

        javax.swing.GroupLayout jPanelEstatisticasLayout = new javax.swing.GroupLayout(jPanelEstatisticas);
        jPanelEstatisticas.setLayout(jPanelEstatisticasLayout);
        jPanelEstatisticasLayout.setHorizontalGroup(
            jPanelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEstatisticasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonGrafoEstatisticas)
                .addGap(108, 108, 108)
                .addComponent(jButtonSubGrafoEstatisticas)
                .addGap(339, 339, 339))
            .addGroup(jPanelEstatisticasLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEstatisticasLayout.createSequentialGroup()
                        .addComponent(jLabelBEsta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBDiaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jButtonObterB))
                    .addGroup(jPanelEstatisticasLayout.createSequentialGroup()
                        .addComponent(jLabelCEsta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonObterC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                            .addComponent(jScrollPane8)))
                    .addGroup(jPanelEstatisticasLayout.createSequentialGroup()
                        .addComponent(jLabelAEst)
                        .addGap(32, 32, 32)
                        .addComponent(jComboBoxA, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelConEsta)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonObterA)
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 271, Short.MAX_VALUE))
        );
        jPanelEstatisticasLayout.setVerticalGroup(
            jPanelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstatisticasLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSubGrafoEstatisticas)
                    .addComponent(jButtonGrafoEstatisticas))
                .addGroup(jPanelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEstatisticasLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAEst)
                            .addComponent(jComboBoxA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelConEsta)
                            .addComponent(jButtonObterA)))
                    .addGroup(jPanelEstatisticasLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(jPanelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBDiaHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBEsta)
                    .addComponent(jButtonObterB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelCEsta)
                        .addComponent(jButtonObterC))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("Estatisticas", jPanelEstatisticas);

        jButtonGrafoFordFulkerson.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButtonGrafoFordFulkerson.setText("Grafo");
        jButtonGrafoFordFulkerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGrafoFordFulkersonActionPerformed(evt);
            }
        });

        jButtonSubGrafoFordFulkerson.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButtonSubGrafoFordFulkerson.setText("SubGrafo");
        jButtonSubGrafoFordFulkerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubGrafoFordFulkersonActionPerformed(evt);
            }
        });

        jLabelOrigemFordFulkerson.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabelOrigemFordFulkerson.setText("Origem:");
        jLabelOrigemFordFulkerson.setToolTipText("");

        jComboBoxOrigemFordFulkerson.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelDestinoFordFulkerson.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabelDestinoFordFulkerson.setText("Destino:");

        jComboBoxDestinoFordFulkerson.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonResultadoFordFulkerson.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButtonResultadoFordFulkerson.setText("Resultado");
        jButtonResultadoFordFulkerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResultadoFordFulkersonActionPerformed(evt);
            }
        });

        jTextAreaFordFulkerson.setEditable(false);
        jTextAreaFordFulkerson.setColumns(20);
        jTextAreaFordFulkerson.setRows(5);
        jScrollPane11.setViewportView(jTextAreaFordFulkerson);

        javax.swing.GroupLayout jPanelFordFulkersonLayout = new javax.swing.GroupLayout(jPanelFordFulkerson);
        jPanelFordFulkerson.setLayout(jPanelFordFulkersonLayout);
        jPanelFordFulkersonLayout.setHorizontalGroup(
            jPanelFordFulkersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFordFulkersonLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addGroup(jPanelFordFulkersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOrigemFordFulkerson)
                    .addComponent(jLabelDestinoFordFulkerson))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanelFordFulkersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxOrigemFordFulkerson, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDestinoFordFulkerson, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(521, 521, 521))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFordFulkersonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonResultadoFordFulkerson)
                .addGap(408, 408, 408))
            .addGroup(jPanelFordFulkersonLayout.createSequentialGroup()
                .addGroup(jPanelFordFulkersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFordFulkersonLayout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jButtonGrafoFordFulkerson)
                        .addGap(168, 168, 168)
                        .addComponent(jButtonSubGrafoFordFulkerson))
                    .addGroup(jPanelFordFulkersonLayout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFordFulkersonLayout.setVerticalGroup(
            jPanelFordFulkersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFordFulkersonLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelFordFulkersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGrafoFordFulkerson)
                    .addComponent(jButtonSubGrafoFordFulkerson))
                .addGap(34, 34, 34)
                .addGroup(jPanelFordFulkersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelOrigemFordFulkerson)
                    .addComponent(jComboBoxOrigemFordFulkerson))
                .addGap(3, 3, 3)
                .addComponent(jButtonResultadoFordFulkerson)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFordFulkersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelDestinoFordFulkerson)
                    .addComponent(jComboBoxDestinoFordFulkerson))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("FordFulkerson", jPanelFordFulkerson);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Faz com que apareça a travesia Dijkstra na textArea, convertendo o grafo de FlowNetwork para EdgeWeightedDigraph
 * @param evt 
 */
    private void jButtonResultadoDijkstraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResultadoDijkstraActionPerformed
        String s[] = this.jComboBoxDOrigem.getSelectedItem().toString().split("-");// Obtem o valor do nó id do nó origem
        int aux = Integer.parseInt(s[0]);
        EdgeWeightedDigraph gDijkstra = new EdgeWeightedDigraph(g.V());
        for(FlowEdge f : g.edges()){
            gDijkstra.addEdge(new DirectedEdge(f.from(),f.to(),f.capacity()));
        }
        DijkstraSP dijMST = new DijkstraSP(gDijkstra,aux);
        s = this.jComboBoxDDestino.getSelectedItem().toString().split("-");// Obtem o valor do nó id do nó de destino
        aux = Integer.parseInt(s[0]);
        if(dijMST.pathTo(aux)==null){
            this.jTextAreaDijkstra.setText("null");
            return;
        }
        for( DirectedEdge e : dijMST.pathTo(aux))
            this.jTextAreaDijkstra.setText(e.toString());
    }//GEN-LAST:event_jButtonResultadoDijkstraActionPerformed

    private void jComboBoxSubGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSubGrafoActionPerformed
        
    }//GEN-LAST:event_jComboBoxSubGrafoActionPerformed
/**
 * Insere os nós selecionados na ComboBox no subGrafo auxiliar
 * @param evt 
 */
    private void jButtonSubGrafoInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubGrafoInserirActionPerformed
        String s[] = this.jComboBoxSubGrafo.getSelectedItem().toString().split("-");// id do nó 
        int aux = Integer.parseInt(s[0]);
        for(NoMoradia gi : g.getNodesM()){
            if(gi.getId()== aux){// procura o nó na lista de nos 
                subGAux.addNode(gi);// adiciona o nó ao grafo auxiliar
                this.jComboBoxSubGrafo.removeItemAt(this.jComboBoxSubGrafo.getSelectedIndex());// remove do ComboBox pois não se pode adicionar outravez o mesmo
            }   
        }
        for(NoFonteEnergia gi : g.getNodesF()){
            if(gi.getId()== aux){
                subGAux.addNode(gi);
                this.jComboBoxSubGrafo.removeItemAt(this.jComboBoxSubGrafo.getSelectedIndex());
            } 
        }

    }//GEN-LAST:event_jButtonSubGrafoInserirActionPerformed
/**
 * Faz as ligações entre os nós que pertencem ao subGrafo auxiliar.
 * Nesta ação é quando o subGrafo é finalizado, isto é, caso adicionem nós e não finalizem não altera nas outras tabs.
 * @param evt 
 */
    private void jButtonSubGrafoFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubGrafoFinalizarActionPerformed
        for(FlowEdge di: this.g.edges())// Procura as arestas que pertencem ao subgrafo, isto é se o nó de origem e detino pertencem ao subgrafo
            if(this.subGAux.pertenceGrafo(di.from())==true && this.subGAux.pertenceGrafo(di.to())==true){
                this.subGAux.addEdge(di);
            } 
        subG = subGAux;// utilizei um grafo auxiliar pois assim caso adicionem nós e não finalizem não altera nas outras tabs
        this.jTextAreaSubGrafo.setText(this.subG.toString());
        this.iniciarJComboBox();
    }//GEN-LAST:event_jButtonSubGrafoFinalizarActionPerformed
/**
 * Faz com que apareça a travesia DFS do grafo nas textAreas, convertendo o grafo de FlowNetwork para EdgeWeightedDigraph.
 * @param evt 
 */
    private void jButtonGrafoDFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGrafoDFSActionPerformed
        EdgeWeightedDigraph gDFS = new EdgeWeightedDigraph(g.V());
        for(FlowEdge f : g.edges()){
            gDFS.addEdge(new DirectedEdge(f.from(),f.to(),f.capacity()));
        }
        DepthFirstOrder dfs = new DepthFirstOrder(gDFS);
        this.jTextAreaPreOrdem.setText(dfs.pre().toString());
        this.jTextAreaPosOrdem.setText(dfs.post().toString());
        this.jTextAreaPosOrdemInv.setText(dfs.reversePost().toString());
    }//GEN-LAST:event_jButtonGrafoDFSActionPerformed
/**
 * Faz com que apareça a travesia DFS do SubGrafo nas textAreas, convertendo o SubGrafo de FlowNetwork para EdgeWeightedDigraph.
 * @param evt 
 */
    private void jButtonDubGrafoDFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDubGrafoDFSActionPerformed
        EdgeWeightedDigraph gDFS = new EdgeWeightedDigraph(g.V());
        for(FlowEdge f : g.edges()){
            gDFS.addEdge(new DirectedEdge(f.from(),f.to(),f.capacity()));
        }
        DepthFirstOrder dfs = new DepthFirstOrder(gDFS);
        this.jTextAreaPreOrdem.setText(dfs.pre().toString());
        this.jTextAreaPosOrdem.setText(dfs.post().toString());
        this.jTextAreaPosOrdemInv.setText(dfs.reversePost().toString());
    }//GEN-LAST:event_jButtonDubGrafoDFSActionPerformed
/**
 * Define alguns componentes como visiveis ou invisiveis e adiciona todos os nós do grafo á ComboBox.
 * @param evt 
 */
    private void jButtonGrafoBellmanFordSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGrafoBellmanFordSPActionPerformed
        this.jComboBoxBellmanFordSP.removeAllItems();
        for(NoMoradia gi : g.getNodesM()){
            this.jComboBoxBellmanFordSP.addItem(gi.getId()+ "-"+gi.getM().toString());
        }
        for(NoFonteEnergia gi : g.getNodesF()){
            this.jComboBoxBellmanFordSP.addItem(gi.getId()+ "-"+gi.getFonte().toString());
        }
        this.jComboBoxBellmanFordSP.setVisible(true);
        this.jButtonSubGrafoBellmanFordSP.setVisible(false);
        this.jTextAreaBellmanFordSP.setVisible(true);
        this.jButtonResultadoBellmanFordSP.setVisible(true);
        this.jLabelOrigemBellmanFordSP.setVisible(true);
        this.jScrollPane6.setVisible(true);
    }//GEN-LAST:event_jButtonGrafoBellmanFordSPActionPerformed
/**
 * Define alguns componentes como visiveis ou invisiveis e adiciona todos os nós do SubGrafo á ComboBox.
 * @param evt 
 */
    private void jButtonSubGrafoBellmanFordSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubGrafoBellmanFordSPActionPerformed
        this.jComboBoxBellmanFordSP.removeAllItems();
        for(NoMoradia gi : subG.getNodesM()){
            this.jComboBoxBellmanFordSP.addItem(gi.getId()+ "-"+gi.getM().toString());
        }
        for(NoFonteEnergia gi : subG.getNodesF()){
            this.jComboBoxBellmanFordSP.addItem(gi.getId()+ "-"+gi.getFonte().toString());
        }
        this.jComboBoxBellmanFordSP.setVisible(true);
        this.jButtonGrafoBellmanFordSP.setVisible(false);
        this.jTextAreaBellmanFordSP.setVisible(true);
        this.jButtonResultadoBellmanFordSP.setVisible(true);
        this.jLabelOrigemBellmanFordSP.setVisible(true);
        this.jScrollPane6.setVisible(true);
    }//GEN-LAST:event_jButtonSubGrafoBellmanFordSPActionPerformed
/**
 * Faz com que apareça a travesia BellmanFordSP do SubGrafo ou do Grafo nas textAreas, convertendo o grafo e o subGrafo de FlowNetwork para EdgeWeightedDigraph.
 * @param evt 
 */
    private void jButtonResultadoBellmanFordSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResultadoBellmanFordSPActionPerformed
        String s[] = this.jComboBoxBellmanFordSP.getSelectedItem().toString().split("-");
        int aux = Integer.parseInt(s[0]);
        this.jTextAreaBellmanFordSP.setText("");
        if(this.jButtonGrafoBellmanFordSP.isVisible()==true){
            EdgeWeightedDigraph gBF = new EdgeWeightedDigraph(g.V());
            for(FlowEdge f : g.edges()){
                gBF.addEdge(new DirectedEdge(f.from(),f.to(),f.capacity()));
            }
            BellmanFordSP sp = new BellmanFordSP(gBF, aux);
            for (int v = 0; v < g.V(); v++) {
                if (sp.hasPathTo(v)) {
                    this.jTextAreaBellmanFordSP.append("\n"+s[0] +" to "+ Integer.toString(v) +"\t"+ Double.toString(sp.distTo(v)));//acrecenta á textArea ao que está lá
                    for (DirectedEdge e : sp.pathTo(v)) {
                        this.jTextAreaBellmanFordSP.append(" "+ e.toString());
                    }
                }
                else {
                    this.jTextAreaBellmanFordSP.append("\n"+s[0]+" to "+ Integer.toString(v)+"\tno path");
                }
            }
        }
        else {
            EdgeWeightedDigraph gBF = new EdgeWeightedDigraph(g.V());
            for(FlowEdge f : subG.edges()){
                gBF.addEdge(new DirectedEdge(f.from(),f.to(),f.capacity()));
                }
            BellmanFordSP sp = new BellmanFordSP(gBF, aux);
            for (int v = 0; v < subG.V(); v++) {
                if (sp.hasPathTo(v)) {
                    this.jTextAreaBellmanFordSP.append("\n"+s[0] +" to "+ Integer.toString(v) +"\t"+ Double.toString(sp.distTo(v)));
                    for (DirectedEdge e : sp.pathTo(v)) {
                        this.jTextAreaBellmanFordSP.append(" "+ e.toString());
                    }
                }
                else {
                    this.jTextAreaBellmanFordSP.append("\n"+s[0]+" to "+ Integer.toString(v)+"\tno path");
                }
            }
        }
    }//GEN-LAST:event_jButtonResultadoBellmanFordSPActionPerformed
/**
 * Evento para restaurar as visibilidades, as comboBox e as textAreas e textField.
 * @param evt 
 */
    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        this.jComboBoxBellmanFordSP.setVisible(false);
        this.jTextAreaBellmanFordSP.setVisible(false);
        this.jButtonResultadoBellmanFordSP.setVisible(false);
        this.jLabelOrigemBellmanFordSP.setVisible(false);
        this.jScrollPane6.setVisible(false);
        this.jButtonGrafoBellmanFordSP.setVisible(true);
        this.jButtonSubGrafoBellmanFordSP.setVisible(true);
        this.jTextAreaBellmanFordSP.setText("");// apaga tudo da textArea
        this.jComboBoxBellmanFordSP.removeAllItems();
        
        this.jButtonResultadoDijkstra.setVisible(false);
        this.jTextAreaDijkstra.setVisible(false);
        this.jComboBoxDDestino.setVisible(false);
        this.jComboBoxDOrigem.setVisible(false);
        this.jLabelDDestino.setVisible(false);
        this.jLabelDOrigem.setVisible(false);
        this.jScrollPane1.setVisible(false);
        this.jTextAreaDijkstra.setText("");
        this.jComboBoxDOrigem.removeAllItems();
        this.jComboBoxDDestino.removeAllItems();
        this.jButtonGrafoDijkstra.setVisible(true);
        this.jButtonSubGrafoDijkstra.setVisible(true);
        
                
        this.jTextAreaPosOrdem.setText("");
        this.jTextAreaPosOrdemInv.setText("");
        this.jTextAreaPreOrdem.setText("");
        
        this.jTextAreaA.setText("");
        this.jTextAreaB.setText("");
        this.jTextAreaC.setText("");
        this.jButtonGrafoEstatisticas.setVisible(true);
        this.jButtonSubGrafoEstatisticas.setVisible(true);
        
        this.jButtonResultadoFordFulkerson.setVisible(false);
        this.jTextAreaFordFulkerson.setVisible(false);
        this.jComboBoxDestinoFordFulkerson.setVisible(false);
        this.jComboBoxOrigemFordFulkerson.setVisible(false);
        this.jLabelDestinoFordFulkerson.setVisible(false);
        this.jLabelOrigemFordFulkerson.setVisible(false);
        this.jScrollPane11.setVisible(false);
        this.jTextAreaFordFulkerson.setText("");
        this.jButtonSubGrafoFordFulkerson.setVisible(true);
    }//GEN-LAST:event_jTabbedPane1MouseClicked
/**
 * Evento para inicializar a comboBox do grafo.
 * @param evt 
 */
    private void jButtonGrafoDijkstraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGrafoDijkstraActionPerformed
        this.jComboBoxDDestino.removeAllItems();
        this.jComboBoxDOrigem.removeAllItems();
        for(NoMoradia gi : g.getNodesM()){
            this.jComboBoxDDestino.addItem(gi.getId()+ "-"+gi.getM().toString());
            this.jComboBoxDOrigem.addItem(gi.getId()+ "-"+gi.getM().toString());
        }
        for(NoFonteEnergia gi : g.getNodesF()){
            this.jComboBoxDOrigem.addItem(gi.getId()+ "-"+gi.getFonte().toString());
            this.jComboBoxDDestino.addItem(gi.getId()+ "-"+gi.getFonte().toString());
        }
        this.jButtonResultadoDijkstra.setVisible(true);
        this.jTextAreaDijkstra.setVisible(true);
        this.jComboBoxDDestino.setVisible(true);
        this.jComboBoxDOrigem.setVisible(true);
        this.jLabelDDestino.setVisible(true);
        this.jLabelDOrigem.setVisible(true);
        this.jScrollPane1.setVisible(true);
        this.jButtonSubGrafoDijkstra.setVisible(false);
    }//GEN-LAST:event_jButtonGrafoDijkstraActionPerformed
/**
 * Evento para inicializar a comboBox do subGrafo.
 * @param evt 
 */
    private void jButtonSubGrafoDijkstraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubGrafoDijkstraActionPerformed
        this.jComboBoxDDestino.removeAllItems();
        this.jComboBoxDOrigem.removeAllItems();
        for(NoMoradia gi : subG.getNodesM()){
            this.jComboBoxDDestino.addItem(gi.getId()+ "-"+gi.getM().toString());
            this.jComboBoxDOrigem.addItem(gi.getId()+ "-"+gi.getM().toString());
        }
        for(NoFonteEnergia gi : subG.getNodesF()){
            this.jComboBoxDOrigem.addItem(gi.getId()+ "-"+gi.getFonte().toString());
            this.jComboBoxDDestino.addItem(gi.getId()+ "-"+gi.getFonte().toString());
        }
        this.jButtonResultadoDijkstra.setVisible(true);
        this.jTextAreaDijkstra.setVisible(true);
        this.jComboBoxDDestino.setVisible(true);
        this.jComboBoxDOrigem.setVisible(true);
        this.jLabelDDestino.setVisible(true);
        this.jLabelDOrigem.setVisible(true);
        this.jScrollPane1.setVisible(true);
        this.jButtonGrafoDijkstra.setVisible(false);
    }//GEN-LAST:event_jButtonSubGrafoDijkstraActionPerformed
/**
 * Evento para escolha de grafo ou subGrafo.
 * @param evt 
 */
    private void jButtonGrafoEstatisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGrafoEstatisticasActionPerformed
        this.jButtonSubGrafoEstatisticas.setVisible(false);
        this.jTextFieldBDiaHora.setEditable(true);
        this.jTextFieldBDiaHora.setToolTipText("Ano/Mes/Dia/Hora/Minuto");
    }//GEN-LAST:event_jButtonGrafoEstatisticasActionPerformed
/**
 * Evento para escolha de grafo ou subGrafo.
 * @param evt 
 */
    private void jButtonSubGrafoEstatisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubGrafoEstatisticasActionPerformed
        this.jButtonGrafoEstatisticas.setVisible(false);
        this.jTextFieldBDiaHora.setEditable(true);
        this.jTextFieldBDiaHora.setToolTipText("Ano/Mes/Dia/Hora/Minuto");
    }//GEN-LAST:event_jButtonSubGrafoEstatisticasActionPerformed
/**
 * Moradias com maior ou menor consumo.
 * @param evt 
 */
    private void jButtonObterAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObterAActionPerformed
        double max = 0.0;
        double min = 100000.0;
        Moradia mMax = g.getNodesM().get(0).getM();
        Moradia mMin = g.getNodesM().get(0).getM();
        if(this.jButtonSubGrafoEstatisticas.isVisible()==false){
            for(NoMoradia n : g.getNodesM()){
                if(max<n.getM().consumoEnergeticoEq()){
                    max = n.getM().consumoEnergeticoEq();
                    mMax = n.getM();
                }
                else{
                    min = n.getM().consumoEnergeticoEq();
                    mMin = n.getM();
                }
            }       
            if(this.jComboBoxA.getSelectedItem().toString().compareTo(">")==0)
                this.jTextAreaA.setText(mMax.toString());
            else
                this.jTextAreaA.setText(mMin.toString());
        }
        else if(this.jButtonGrafoEstatisticas.isVisible()==false){
            for(NoMoradia n : subG.getNodesM()){
                if(max<n.getM().consumoEnergeticoEq()){
                    max = n.getM().consumoEnergeticoEq();
                    mMax = n.getM();
                }
                else{
                    min = n.getM().consumoEnergeticoEq();
                    mMin = n.getM();
                }
            }       
            if(this.jComboBoxA.getSelectedItem().toString().compareTo(">")==0)
                this.jTextAreaA.setText(mMax.toString());
            else
                this.jTextAreaA.setText(mMin.toString());
        }
    }//GEN-LAST:event_jButtonObterAActionPerformed
/**
 * Moradias com consumo num dia e hora.
 * @param evt 
 */
    private void jButtonObterBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObterBActionPerformed
        String[] s = this.jTextFieldBDiaHora.getText().split("/");// ano/mes/dia/hora/min
        Date d =  new Date(Integer.parseInt(s[0]),Integer.parseInt(s[1]),Integer.parseInt(s[2]),Integer.parseInt(s[3]),Integer.parseInt(s[4]));
        this.jTextAreaB.setText("");
        if(this.jButtonSubGrafoEstatisticas.isVisible()==false){
            for(NoMoradia n : g.getNodesM())
                for (int eq : n.getM().getEquipamentos().keys()){
                    Equipamento e = n.getM().getEquipamentos().get(eq);
                    for(Date di : e.getHistoricos().keys())
                        if(di.compareTo(d)<=0){
                            HistoricoConsumo h = e.getHistoricos().get(di);
                            if(h.getFim().compareTo(d)>=0){
                                this.jTextAreaB.append(n.getM().toString() + "\n");
                            }
                        }
                }
        }
        else if(this.jButtonGrafoEstatisticas.isVisible()==false){
            for(NoMoradia n : subG.getNodesM())
                for (int eq : n.getM().getEquipamentos().keys()){
                    Equipamento e = n.getM().getEquipamentos().get(eq);
                    for(Date di : e.getHistoricos().keys())
                        if(di.compareTo(d)<=0){
                            HistoricoConsumo h = e.getHistoricos().get(di);
                            if(h.getFim().compareTo(d)>=0){
                                this.jTextAreaB.append(n.getM().toString() + "\n");
                            }
                        }
                }
        }
        this.jTextFieldBDiaHora.setText("");
    }//GEN-LAST:event_jButtonObterBActionPerformed
/**
 * Moradias eficientes.
 * @param evt 
 */
    private void jButtonObterCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObterCActionPerformed
        if(this.jButtonSubGrafoEstatisticas.isVisible()==false){
            for(NoMoradia n : g.getNodesM())
                if(n.getM().getAutonomia()==true)
                    this.jTextAreaC.append(n.getM().toString()+"\n");
        }
        else if(this.jButtonGrafoEstatisticas.isVisible()==false){
            for(NoMoradia n : subG.getNodesM())
                if(n.getM().getAutonomia()==true)
                    this.jTextAreaC.append(n.getM().toString()+"\n");
        }
    }//GEN-LAST:event_jButtonObterCActionPerformed
/**
 * Sempre que se altera o que queremos ver a textArea é inicilizada com "".
 * @param evt 
 */
    private void jComboBoxAItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxAItemStateChanged
        this.jTextAreaA.setText("");
    }//GEN-LAST:event_jComboBoxAItemStateChanged
/**
 * Evento para inicializar a comboBox do grafo e alterar visibilidade.
 * @param evt 
 */
    private void jButtonGrafoFordFulkersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGrafoFordFulkersonActionPerformed
        this.jComboBoxDestinoFordFulkerson.removeAllItems();
        this.jComboBoxOrigemFordFulkerson.removeAllItems();
        for(NoMoradia gi : g.getNodesM()){
            this.jComboBoxDestinoFordFulkerson.addItem(gi.getId()+ "-"+gi.getM().toString());
            this.jComboBoxOrigemFordFulkerson.addItem(gi.getId()+ "-"+gi.getM().toString());
        }
        for(NoFonteEnergia gi : g.getNodesF()){
            this.jComboBoxOrigemFordFulkerson.addItem(gi.getId()+ "-"+gi.getFonte().toString());
            this.jComboBoxDestinoFordFulkerson.addItem(gi.getId()+ "-"+gi.getFonte().toString());
        }
        this.jButtonResultadoFordFulkerson.setVisible(true);
        this.jTextAreaFordFulkerson.setVisible(true);
        this.jComboBoxDestinoFordFulkerson.setVisible(true);
        this.jComboBoxOrigemFordFulkerson.setVisible(true);
        this.jLabelDestinoFordFulkerson.setVisible(true);
        this.jLabelOrigemFordFulkerson.setVisible(true);
        this.jScrollPane11.setVisible(true);
        this.jButtonSubGrafoFordFulkerson.setVisible(false);
    }//GEN-LAST:event_jButtonGrafoFordFulkersonActionPerformed
/**
 * Evento para inicializar a comboBox do subGrafo e alterar visibilidade.
 * @param evt 
 */
    private void jButtonSubGrafoFordFulkersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubGrafoFordFulkersonActionPerformed
        this.jComboBoxDestinoFordFulkerson.removeAllItems();
        this.jComboBoxOrigemFordFulkerson.removeAllItems();
        for(NoMoradia gi : subG.getNodesM()){
            this.jComboBoxDestinoFordFulkerson.addItem(gi.getId()+ "-"+gi.getM().toString());
            this.jComboBoxOrigemFordFulkerson.addItem(gi.getId()+ "-"+gi.getM().toString());
        }
        for(NoFonteEnergia gi : subG.getNodesF()){
            this.jComboBoxOrigemFordFulkerson.addItem(gi.getId()+ "-"+gi.getFonte().toString());
            this.jComboBoxDestinoFordFulkerson.addItem(gi.getId()+ "-"+gi.getFonte().toString());
        }
        this.jButtonResultadoFordFulkerson.setVisible(true);
        this.jTextAreaFordFulkerson.setVisible(true);
        this.jComboBoxDestinoFordFulkerson.setVisible(true);
        this.jComboBoxOrigemFordFulkerson.setVisible(true);
        this.jLabelDestinoFordFulkerson.setVisible(true);
        this.jLabelOrigemFordFulkerson.setVisible(true);
        this.jScrollPane11.setVisible(true);
        this.jButtonGrafoFordFulkerson.setVisible(false);
    }//GEN-LAST:event_jButtonSubGrafoFordFulkersonActionPerformed
/**
 * Faz com que apareça a travesia FordFulkerson na textArea.
 * @param evt 
 */
    private void jButtonResultadoFordFulkersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResultadoFordFulkersonActionPerformed
        int origem, destino;
        String s[];
        if(this.jButtonSubGrafoFordFulkerson.isVisible()==false){
            s  = this.jComboBoxOrigemFordFulkerson.getSelectedItem().toString().split("-");
            origem = Integer.parseInt(s[0]);
            s  = this.jComboBoxDestinoFordFulkerson.getSelectedItem().toString().split("-");
            destino = Integer.parseInt(s[0]);
            FordFulkerson maxflow = new FordFulkerson(g, origem, destino);
            this.jTextAreaFordFulkerson.append("Fluxo máximo de " + origem + " para " + destino);
            if(maxflow.value()==0){
                this.jTextAreaFordFulkerson.append("\nnull");
                return;
            }
            for (int v = 0; v < g.V(); v++) {
                for (FlowEdge e : g.adj(v)) {
                    if ((v == e.from()) && e.flow() > 0) {
                        this.jTextAreaFordFulkerson.append("\n" + e.toString());
                    }
                }
            }
            this.jTextAreaFordFulkerson.append("\n\nMin cut: ");
            for (int v = 0; v < g.V(); v++) {
                if (maxflow.inCut(v)) {
                    this.jTextAreaFordFulkerson.append(v + " ");
                }
            }
            this.jTextAreaFordFulkerson.append("\n\nValor máximo de fluxo = " + maxflow.value());
        }
        else{
            s  = this.jComboBoxOrigemFordFulkerson.getSelectedItem().toString().split("-");
            origem = Integer.parseInt(s[0]);
            s  = this.jComboBoxDestinoFordFulkerson.getSelectedItem().toString().split("-");
            destino = Integer.parseInt(s[0]);
            FordFulkerson maxflow = new FordFulkerson(subG, origem, destino);
            this.jTextAreaFordFulkerson.append("Fluxo máximo de " + origem + " para " + destino);
            if(maxflow.value()==0){
                this.jTextAreaFordFulkerson.append("\nnull");
                return;
            }
            for (int v = 0; v < subG.V(); v++) {
                for (FlowEdge e : subG.adj(v)) {
                    if ((v == e.from()) && e.flow() > 0) {
                        this.jTextAreaFordFulkerson.append("\n" + e.toString());
                    }
                }
            }
            this.jTextAreaFordFulkerson.append("\n\nMin cut: ");
            for (int v = 0; v < subG.V(); v++) {
                if (maxflow.inCut(v)) {
                    this.jTextAreaFordFulkerson.append(v + " ");
                }
            }
            this.jTextAreaFordFulkerson.append("\n\nValor máximo de fluxo = " + maxflow.value());
        }
    }//GEN-LAST:event_jButtonResultadoFordFulkersonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new interfaceGrafica().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(interfaceGrafica.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(interfaceGrafica.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDubGrafoDFS;
    private javax.swing.JButton jButtonGrafoBellmanFordSP;
    private javax.swing.JButton jButtonGrafoDFS;
    private javax.swing.JButton jButtonGrafoDijkstra;
    private javax.swing.JButton jButtonGrafoEstatisticas;
    private javax.swing.JButton jButtonGrafoFordFulkerson;
    private javax.swing.JButton jButtonObterA;
    private javax.swing.JButton jButtonObterB;
    private javax.swing.JButton jButtonObterC;
    private javax.swing.JButton jButtonResultadoBellmanFordSP;
    private javax.swing.JButton jButtonResultadoDijkstra;
    private javax.swing.JButton jButtonResultadoFordFulkerson;
    private javax.swing.JButton jButtonSubGrafoBellmanFordSP;
    private javax.swing.JButton jButtonSubGrafoDijkstra;
    private javax.swing.JButton jButtonSubGrafoEstatisticas;
    private javax.swing.JButton jButtonSubGrafoFinalizar;
    private javax.swing.JButton jButtonSubGrafoFordFulkerson;
    private javax.swing.JButton jButtonSubGrafoInserir;
    private javax.swing.JComboBox<String> jComboBoxA;
    private javax.swing.JComboBox<String> jComboBoxBellmanFordSP;
    private javax.swing.JComboBox<String> jComboBoxDDestino;
    private javax.swing.JComboBox<String> jComboBoxDOrigem;
    private javax.swing.JComboBox<String> jComboBoxDestinoFordFulkerson;
    private javax.swing.JComboBox<String> jComboBoxOrigemFordFulkerson;
    private javax.swing.JComboBox<String> jComboBoxSubGrafo;
    private javax.swing.JLabel jLabelAEst;
    private javax.swing.JLabel jLabelBEsta;
    private javax.swing.JLabel jLabelCEsta;
    private javax.swing.JLabel jLabelConEsta;
    private javax.swing.JLabel jLabelDDestino;
    private javax.swing.JLabel jLabelDOrigem;
    private javax.swing.JLabel jLabelDestinoFordFulkerson;
    private javax.swing.JLabel jLabelOrigemBellmanFordSP;
    private javax.swing.JLabel jLabelOrigemFordFulkerson;
    private javax.swing.JLabel jLabelPosOrdem;
    private javax.swing.JLabel jLabelPosOrdemInv;
    private javax.swing.JLabel jLabelPreOrdem;
    private javax.swing.JPanel jPanelBellmanFord;
    private javax.swing.JPanel jPanelDFS;
    private javax.swing.JPanel jPanelDijkstra;
    private javax.swing.JPanel jPanelEstatisticas;
    private javax.swing.JPanel jPanelFordFulkerson;
    private javax.swing.JPanel jPanelGrafo;
    private javax.swing.JPanel jPanelSubGrafo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextAreaA;
    private javax.swing.JTextArea jTextAreaB;
    private javax.swing.JTextArea jTextAreaBellmanFordSP;
    private javax.swing.JTextArea jTextAreaC;
    private javax.swing.JTextArea jTextAreaDijkstra;
    private javax.swing.JTextArea jTextAreaFordFulkerson;
    private javax.swing.JTextArea jTextAreaGrafo;
    private javax.swing.JTextArea jTextAreaPosOrdem;
    private javax.swing.JTextArea jTextAreaPosOrdemInv;
    private javax.swing.JTextArea jTextAreaPreOrdem;
    private javax.swing.JTextArea jTextAreaSubGrafo;
    private javax.swing.JTextField jTextFieldBDiaHora;
    // End of variables declaration//GEN-END:variables
}
